pull_request_rules:
  - name: Automatic merge on CI
    conditions:
      - or:
        - base=main
        - base=dev
      - "status-success=test"
      - "status-success=build"
    actions:
      merge:
        method: merge
